from .dashboard import Dashboard
from .db_config import Database
from .analytics import Analytics
from .all_reservation import Reservation
from .housekeeping import Housekeeping
from .rates_availability import RatesAndAvailability
from .accounting import Accounting
from .alert import Alerts
from .revenue_mgmt import RevenueMgmt
from .admin import Admin
from .email_sender import OTPVerification
from .login import Login
from .staff_mgmt import Staff_Management